global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'node_app_http'
    static_configs:
      - targets: ['web:4000']
  - job_name: 'node_app_metrics'
    static_configs:
        - targets: ['localhost:4000'] 
    metrics_path: '/metrics' 
    scrape_interval: 10s



